[package]
name = "bleique"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "bleique"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
blake3 = "1.3.3"
bytes = "1.3.0"
hex-literal = "0.3.4"
rustler = "0.26.0"
